In [114]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.feature_selection import VarianceThreshold
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
#warning ignore
import warnings
warnings.filterwarnings('ignore')

#load airline_seat dataset

In [115]:
df=pd.read_csv('/content/Airline _Seat_Payment_Data Set.csv')
df

,pax_name,pax_passport,seg_route_from,seg_route_to,seg_flight,seg_cabin,seg_dep_time,pax_fcny,pax_tax,emd_lable,...,pit_pay_avg_amt_m3,pit_pay_avg_amt_m6,pit_pay_avg_amt_y1,pit_pay_avg_amt_y2,pit_pay_avg_amt_y3,pit_add_chnl_m3,pit_add_chnl_m6,pit_add_chnl_y1,pit_add_chnl_y2,pit_add_chnl_y3
0,9612c51f08718e48b1361e415ef55be9,93d0aceeaef3f85264e5c5b5b1148a90,PVG,JFK,AB1006,J,2018/12/16 20:00,4161.0,584.43,0,...,0,0.0,0.0,0.0,0.0,0,0,0,0,0
1,c7ca533cd9da4c4bf3d597248f90bc6e,6930f6fa59d86c11fa28c610ab6f56a5,PVG,JFK,AB1006,J,2019/2/18 20:00,1670.0,248.80,1,...,0,0.0,0.0,0.0,0.0,0,0,0,0,0
2,bd2cb6b0dd56fb3de6f7c018296a07e2,da73afa8f6ededd29d67a9331dccdbe9,PVG,LAX,AB1009,Y,2018/3/9 13:20,243.0,301.31,1,...,0,0.0,0.0,0.0,0.0,0,0,0,0,0
3,65657872fe131ea7651565638dcb5683,dc31eead23771810dbb586ad236ade3b,PVG,LAX,AB1009,Y,2018/1/2 13:20,1362.0,454.16,0,...,0,0.0,0.0,0.0,0.0,0,0,0,0,0
4,722261f7b860b183da9fe0b6630b6dbf,7689603247539830a08d945cb1a57823,PVG,JFK,AB1010,Y,2018/7/6 11:30,675.0,284.11,1,...,0,0.0,0.0,0.0,0.0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23427,ec988e914b272ad74634c52b71e84ea8,e61b68ce193bce838436620230ce94e1,PVG,SYD,AB1007,Y,2017/8/1 20:20,807.0,486.50,0,...,0,0.0,0.0,0.0,0.0,0,0,0,0,0
23428,fa23535ab2ca52589303bd265ee6d382,fdd824109fccadfbcba782aaae72484f,PVG,SYD,AB1007,J,2017/3/25 20:20,2218.0,312.90,0,...,0,0.0,0.0,0.0,0.0,0,0,0,0,0
23429,623d32d20af6c9752d8eef46efe95c09,ef53ebb9358d5c7b013f6aed92d78a42,PVG,SYD,AB1007,J,2017/3/25 20:20,2218.0,312.90,0,...,0,0.0,0.0,0.0,0.0,0,0,0,0,0
23430,dadbf45dde7347740b0294c2c0913100,5fe336074ba73e83e12dccb31c33fe40,PVG,SYD,AB1007,J,2017/3/25 20:20,2218.0,312.90,0,...,0,0.0,0.0,0.0,0.0,0,0,0,0,0
23431,d4ca366192c096cdda1be87ad0bb89b5,b3981b746d87f6fcea1dba9059d6678f,PVG,SYD,AB1007,J,2017/2/26 20:20,4900.0,744.76,0,...,0,0.0,0.0,0.0,0.0,0,0,0,0,0

In [116]:
# Check for missing values
df.isnull().sum()

pax_name           0
pax_passport       0
seg_route_from     0
seg_route_to       0
seg_flight         0
                  ..
pit_add_chnl_m3    0
pit_add_chnl_m6    0
pit_add_chnl_y1    0
pit_add_chnl_y2    0
pit_add_chnl_y3    0
Length: 657, dtype: int64

There are missing value can't visible

In [117]:
# Check for missing values
missing_values = df.isnull().sum()
print("\nMissing values in each column:")
print(missing_values[missing_values > 0])

Missing values in each column:
seg_cabin    1
city_name    4
dtype: int64

In [118]:
# Drop  all missing values rows
df.dropna(inplace=True)

In [119]:
df.shape

(23427, 657)

In [120]:
#check the duplicated rows
df.duplicated().sum()

51

In [121]:
df.shape

(23427, 657)

In [122]:
# Remove duplicated rows if any
df=df.drop_duplicates()

In [123]:
df.shape

(23376, 657)

In [124]:
#copy dataset
df1=df.copy()

In [125]:
#Remove unnecessary columns
df = df.drop(columns=['pax_name', 'pax_passport','birth_date'])

In [126]:
#check ths categorical dataset
columns=df.select_dtypes(include=['object']).columns

In [127]:
# Apply Label Encoding to each categorical column
label_encoder = LabelEncoder()
for column in columns:
    df[column] = label_encoder.fit_transform(df[column].astype(str))

##***Feature Selection:-***

#1.Remove Duplicated columns in dataset:-

In [128]:
#check duplicated columns
df.T.duplicated()

seg_route_from     False
seg_route_to       False
seg_flight         False
seg_cabin          False
seg_dep_time       False
                   ...
pit_add_chnl_m3    False
pit_add_chnl_m6    False
pit_add_chnl_y1    False
pit_add_chnl_y2    False
pit_add_chnl_y3    False
Length: 654, dtype: bool

In [129]:
df.columns[df.T.duplicated()]

Index(['often_city', 'seat_safe_cnt_m3', 'seat_safe_cnt_m6',
       'seat_safe_cnt_y1', 'seat_safe_cnt_y2', 'seat_safe_cnt_y3',
       'workday_cnt_m3', 'workday_cnt_m6', 'workday_cnt_y1', 'workday_cnt_y2',
       ...
       'pit_income_avg_amt_m3', 'pit_income_avg_amt_m6',
       'pit_income_avg_amt_y1', 'pit_income_avg_amt_y2',
       'pit_income_avg_amt_y3', 'pit_pay_avg_amt_m3', 'pit_pay_avg_amt_m6',
       'pit_pay_avg_amt_y1', 'pit_pay_avg_amt_y2', 'pit_pay_avg_amt_y3'],
      dtype='object', length=143)

In [130]:
#get duplicated columns
duplicated_cols = df.columns[df.T.duplicated()]
print(duplicated_cols)

Index(['often_city', 'seat_safe_cnt_m3', 'seat_safe_cnt_m6',
       'seat_safe_cnt_y1', 'seat_safe_cnt_y2', 'seat_safe_cnt_y3',
       'workday_cnt_m3', 'workday_cnt_m6', 'workday_cnt_y1', 'workday_cnt_y2',
       ...
       'pit_income_avg_amt_m3', 'pit_income_avg_amt_m6',
       'pit_income_avg_amt_y1', 'pit_income_avg_amt_y2',
       'pit_income_avg_amt_y3', 'pit_pay_avg_amt_m3', 'pit_pay_avg_amt_m6',
       'pit_pay_avg_amt_y1', 'pit_pay_avg_amt_y2', 'pit_pay_avg_amt_y3'],
      dtype='object', length=143)

In [131]:
#find number of duplicated columns
duplicated_cols.shape

(143,)

In [132]:
# Remove the duplicated columns
df = df.drop(columns=duplicated_cols)

In [133]:
df.shape

(23376, 511)

#2.Apply VarianceThreshold:

In [134]:
model=VarianceThreshold(threshold=0.02)

In [135]:
# Apply VarianceThreshold to remove low-variance features
df_vt=model.fit(df)

In [136]:
#get column pass the variance or not
df_vt.get_support()

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False, False, False, False,  True,
        True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False,  True, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False,  True,  True, False, False, False, False, False, False,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False, False, False, False, False, False,  True,  True, False,
       False, False, False,  True, False, False, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True, False,  True,  True,  True,  True])

In [137]:
#get column  name from this df_vt.get_support() values =True store in columns
columns=df.columns[df_vt.get_support()]
columns

Index(['seg_route_to', 'seg_flight', 'seg_cabin', 'seg_dep_time', 'pax_fcny',
       'pax_tax', 'emd_lable', 'emd_lable2', 'gender', 'age',
       ...
       'pit_income_cnt_y1', 'pit_income_cnt_y2', 'pit_income_cnt_y3',
       'pit_pay_cnt_y1', 'pit_pay_cnt_y2', 'pit_pay_cnt_y3', 'pit_add_chnl_m6',
       'pit_add_chnl_y1', 'pit_add_chnl_y2', 'pit_add_chnl_y3'],
      dtype='object', length=444)

In [138]:
#transfom the data in variance theshold which is array format
df_vt=df_vt.transform(df)

In [139]:
#convert array dataset to   dataframe
df=pd.DataFrame(df_vt,columns=columns)

In [140]:
df.shape

(23376, 444)

#3.Correlation feature selection

In [141]:
# Calculate correlation matrix
corr_matrix = df.corr().abs()

# Select upper triangle of the correlation matrix
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

# Find features with correlation greater than a threshold (e.g., 0.9)
to_drop_col = [column for column in upper.columns if any(upper[column] > 0.9)]

# Print the columns to be dropped
print("Columns to be dropped:")
print(to_drop_col)

Columns to be dropped:
['enroll_chnl', 'cabin_hf_cnt_y3', 'cabin_f_cnt_y3', 'cabin_hy_cnt_y3', 'cabin_y_cnt_y3', 'cabin_c_cnt_m6', 'cabin_c_cnt_y1', 'cabin_c_cnt_y2', 'cabin_c_cnt_y3', 'pref_aircraft_m3_2', 'pref_aircraft_m3_3', 'pref_aircraft_m3_4', 'pref_aircraft_m3_5', 'pref_aircraft_m6_4', 'pref_aircraft_m6_5', 'pref_aircraft_y1_4', 'pref_aircraft_y1_5', 'pref_aircraft_y2_5', 'pref_aircraft_y3_5', 'seat_window_cnt_y3', 'seat_walkway_cnt_y3', 'prebuy_d_cnt_m6_d3', 'prebuy_d_cnt_y1_d3', 'prebuy_d_cnt_y2_d3', 'prebuy_d_cnt_y2_d7', 'prebuy_d_cnt_y2_d14', 'prebuy_d_cnt_y3_d3', 'prebuy_d_cnt_y3_d7', 'prebuy_d_cnt_y3_d14', 'prebuy_d_cnt_y3_d30', 'prebuy_i_cnt_y2_d30', 'prebuy_i_cnt_y3_d7', 'prebuy_i_cnt_y3_d14', 'prebuy_i_cnt_y3_d30', 'prebuy_i_cnt_y3_d99', 'pref_orig_m3_2', 'pref_orig_m3_4', 'pref_orig_m3_5', 'pref_orig_m6_2', 'pref_orig_m6_5', 'pref_orig_y1_2', 'pref_orig_y1_5', 'pref_orig_y2_2', 'pref_orig_y3_2', 'pref_line_m3_5', 'pref_city_m3_2', 'pref_city_m3_4', 'pref_city_m3_5', 'pref_city_m6_2', 'pref_city_m6_4', 'pref_city_m6_5', 'pref_city_y1_1', 'pref_city_y1_2', 'pref_city_y1_5', 'pref_city_y2_2', 'pref_city_y3_2', 'pref_month_m3_2', 'pref_month_m3_4', 'pref_month_m3_5', 'pref_month_m6_1', 'pref_month_m6_2', 'pref_month_m6_4', 'pref_month_m6_5', 'pref_month_y1_4', 'pref_month_y1_5', 'pref_month_y2_5', 'pref_month_y3_5', 'flt_cnt_y1', 'flt_cnt_y2', 'flt_cnt_y3', 'recent_flt_day', 'flt_nature_cnt_y3', 'avg_dist_cnt_y3', 'complain_valid_cnt_y3', 'cabin_upgrd_cnt_y2', 'cabin_upgrd_cnt_y3', 'select_seat_cnt_y3', 'dist_d_cnt_m6', 'dist_d_cnt_y1', 'dist_d_cnt_y2', 'dist_d_cnt_y3', 'dist_i_cnt_y2', 'dist_i_cnt_y3', 'dist_all_cnt_m3', 'dist_all_cnt_m6', 'dist_all_cnt_y1', 'dist_all_cnt_y2', 'cabin_hd_cnt_m6', 'cabin_hd_cnt_y1', 'cabin_hd_cnt_y2', 'cabin_hd_cnt_y3', 'cabin_hi_cnt_m6', 'cabin_hi_cnt_y1', 'cabin_hi_cnt_y2', 'cabin_hi_cnt_y3', 'flt_leg_cnt_y1', 'flt_leg_cnt_y2', 'flt_leg_i_cnt_m6', 'flt_leg_i_cnt_y1', 'flt_leg_i_cnt_y2', 'flt_leg_i_cnt_y3', 'flt_leg_d_cnt_m3', 'flt_leg_d_cnt_m6', 'flt_leg_d_cnt_y1', 'flt_leg_d_cnt_y2', 'flt_leg_d_cnt_y3', 'flt_delay_cnt_y3', 'flt_delay_time_m6', 'flt_delay_time_y1', 'flt_delay_time_y2', 'pref_orig_city_m3', 'pref_orig_city_m6', 'pref_orig_city_y1', 'pref_orig_city_y2', 'pref_orig_city_y3', 'pref_dest_city_m3', 'pref_dest_city_m6', 'pref_dest_city_y1', 'pref_dest_city_y2', 'pref_dest_city_y3', 'flt_bag_cnt_y3', 'complain_cnt_y1', 'complain_cnt_y2', 'complain_cnt_y3', 'tkt_d_amt_m3', 'tkt_d_amt_m6', 'tkt_d_amt_y1', 'tkt_d_amt_y2', 'tkt_d_amt_y3', 'tkt_i_amt_y3', 'tkt_all_amt_m3', 'tkt_all_amt_m6', 'tkt_all_amt_y1', 'tkt_all_amt_y2', 'tkt_all_amt_y3', 'tkt_return_cnt_y3', 'tkt_book_cnt_y1', 'tkt_book_cnt_y2', 'tkt_book_cnt_y3', 'tkt_return_all_cnt_y3', 'pit_accu_amt_y2', 'pit_accu_amt_y3', 'pit_cons_amt_y3', 'pit_avg_accu_amt_y3', 'pit_avg_cons_amt_m6', 'pit_avg_cons_amt_y3', 'pit_cons_cnt_y3', 'pit_add_air_amt_m3', 'pit_add_air_amt_y1', 'pit_add_air_amt_y2', 'pit_add_air_amt_y3', 'pit_add_non_amt_y1', 'pit_add_non_amt_y2', 'pit_add_non_amt_y3', 'pit_add_buy_amt_y3', 'pit_des_upg_amt_y2', 'pit_des_upg_amt_y3', 'pit_des_mall_amt_y3', 'pit_add_air_cnt_y1', 'pit_add_air_cnt_y2', 'pit_add_air_cnt_y3', 'pit_add_non_cnt_y3', 'pit_des_upg_cnt_y2', 'pit_des_upg_cnt_y3', 'pit_des_out_cnt_y3', 'pit_avg_amt_m3', 'pit_avg_amt_y3', 'pit_ech_avg_amt_m3', 'pit_ech_avg_amt_y3', 'pit_income_cnt_y1', 'pit_income_cnt_y2', 'pit_income_cnt_y3', 'pit_pay_cnt_y3', 'pit_add_chnl_y3']

In [142]:
df=df.drop(columns=to_drop_col)

In [143]:
#check the number of column left
df.shape[1]

270

In [144]:
df.head()

,seg_route_to,seg_flight,seg_cabin,seg_dep_time,pax_fcny,pax_tax,emd_lable,emd_lable2,gender,age,...,pit_out_avg_amt_m6,pit_out_avg_amt_y1,pit_out_avg_amt_y2,pit_out_avg_amt_y3,pit_income_cnt_m6,pit_pay_cnt_y1,pit_pay_cnt_y2,pit_add_chnl_m6,pit_add_chnl_y1,pit_add_chnl_y2
0,0.0,6.0,2.0,2141.0,4161.0,584.43,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,6.0,2.0,4289.0,1670.0,248.80,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,9.0,4.0,2665.0,243.0,301.31,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,9.0,4.0,1556.0,1362.0,454.16,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,10.0,4.0,3354.0,675.0,284.11,1.0,1.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

#4.Feature Clustering

In [145]:
from sklearn.cluster import FeatureAgglomeration

# Apply Feature Agglomeration
fa = FeatureAgglomeration(n_clusters=100)  # Adjust the number of clusters as needed
data_reduced = fa.fit(df)

In [146]:
#extract columns
columns=data_reduced.get_feature_names_out()
columns

array(['featureagglomeration0', 'featureagglomeration1',
       'featureagglomeration2', 'featureagglomeration3',
       'featureagglomeration4', 'featureagglomeration5',
       'featureagglomeration6', 'featureagglomeration7',
       'featureagglomeration8', 'featureagglomeration9',
       'featureagglomeration10', 'featureagglomeration11',
       'featureagglomeration12', 'featureagglomeration13',
       'featureagglomeration14', 'featureagglomeration15',
       'featureagglomeration16', 'featureagglomeration17',
       'featureagglomeration18', 'featureagglomeration19',
       'featureagglomeration20', 'featureagglomeration21',
       'featureagglomeration22', 'featureagglomeration23',
       'featureagglomeration24', 'featureagglomeration25',
       'featureagglomeration26', 'featureagglomeration27',
       'featureagglomeration28', 'featureagglomeration29',
       'featureagglomeration30', 'featureagglomeration31',
       'featureagglomeration32', 'featureagglomeration33',
       'featureagglomeration34', 'featureagglomeration35',
       'featureagglomeration36', 'featureagglomeration37',
       'featureagglomeration38', 'featureagglomeration39',
       'featureagglomeration40', 'featureagglomeration41',
       'featureagglomeration42', 'featureagglomeration43',
       'featureagglomeration44', 'featureagglomeration45',
       'featureagglomeration46', 'featureagglomeration47',
       'featureagglomeration48', 'featureagglomeration49',
       'featureagglomeration50', 'featureagglomeration51',
       'featureagglomeration52', 'featureagglomeration53',
       'featureagglomeration54', 'featureagglomeration55',
       'featureagglomeration56', 'featureagglomeration57',
       'featureagglomeration58', 'featureagglomeration59',
       'featureagglomeration60', 'featureagglomeration61',
       'featureagglomeration62', 'featureagglomeration63',
       'featureagglomeration64', 'featureagglomeration65',
       'featureagglomeration66', 'featureagglomeration67',
       'featureagglomeration68', 'featureagglomeration69',
       'featureagglomeration70', 'featureagglomeration71',
       'featureagglomeration72', 'featureagglomeration73',
       'featureagglomeration74', 'featureagglomeration75',
       'featureagglomeration76', 'featureagglomeration77',
       'featureagglomeration78', 'featureagglomeration79',
       'featureagglomeration80', 'featureagglomeration81',
       'featureagglomeration82', 'featureagglomeration83',
       'featureagglomeration84', 'featureagglomeration85',
       'featureagglomeration86', 'featureagglomeration87',
       'featureagglomeration88', 'featureagglomeration89',
       'featureagglomeration90', 'featureagglomeration91',
       'featureagglomeration92', 'featureagglomeration93',
       'featureagglomeration94', 'featureagglomeration95',
       'featureagglomeration96', 'featureagglomeration97',
       'featureagglomeration98', 'featureagglomeration99'], dtype=object)

In [147]:
#transform dataset
df_reduced=data_reduced.transform(df)

In [148]:
#convert thein to df
df_red=pd.DataFrame(df_reduced,columns=columns)

In [149]:
df_red.shape

(23376, 100)

In [150]:
df_red

,featureagglomeration0,featureagglomeration1,featureagglomeration2,featureagglomeration3,featureagglomeration4,featureagglomeration5,featureagglomeration6,featureagglomeration7,featureagglomeration8,featureagglomeration9,...,featureagglomeration90,featureagglomeration91,featureagglomeration92,featureagglomeration93,featureagglomeration94,featureagglomeration95,featureagglomeration96,featureagglomeration97,featureagglomeration98,featureagglomeration99
0,0.0,0.0,0.0,0.065693,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,584.43,0.0,0.0,0.0,0.0
1,0.0,12.5,0.0,0.240876,0.0,41.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3253.556667,0.0,248.80,247.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.116788,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,301.31,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.211679,0.0,19.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,4515.030000,21.5,454.16,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.233577,0.0,0.0,0.0,0.0,57.0,0.0,...,0.0,0.0,0.0,0.000000,44.5,284.11,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23371,0.0,0.0,0.0,0.102190,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,486.50,0.0,0.0,0.0,0.0
23372,0.0,0.0,0.0,0.087591,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,312.90,0.0,0.0,0.0,0.0
23373,0.0,0.0,0.0,0.087591,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,312.90,0.0,0.0,0.0,0.0
23374,0.0,0.0,0.0,0.087591,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,312.90,0.0,0.0,0.0,0.0
23375,0.0,0.0,0.0,0.087591,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,744.76,0.0,0.0,0.0,0.0

#4. Principal Component Analysis (PCA)

In [151]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [152]:
scaler = StandardScaler()
df_scaled = scaler.fit(df)

In [153]:
df_scaled

StandardScaler()

In [154]:
#transform dataset
df_scaled=df_scaled.transform(df)

In [156]:
n_components = 50  # Adjust the number of components as needed
pca = PCA(n_components=n_components)
pca_data = pca.fit_transform(df_scaled)

In [158]:
# Convert to DataFrame and create new column names
pca_columns = [f'PC{i+1}' for i in range(50)]  # Naming columns as PC1, PC2, ...
pca_df = pd.DataFrame(pca_data, columns=pca_columns)

In [160]:
pca_df

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,...,PC41,PC42,PC43,PC44,PC45,PC46,PC47,PC48,PC49,PC50
0,-3.245863,0.138346,1.974449,-0.456095,0.969124,-0.717121,-0.233973,0.209838,-0.327741,-0.315775,...,0.367740,0.207858,-0.751583,0.414000,0.713034,0.335237,-0.138202,-0.439712,0.107749,-0.001924
1,1.374972,-5.007862,-2.031361,2.653046,0.973394,-0.301208,-1.609041,-0.565236,1.498271,0.495366,...,1.056395,1.697580,-0.518860,-0.762472,-0.231312,-0.580783,0.312157,1.118722,0.773370,0.038646
2,-3.299550,0.132167,1.974033,-0.513229,1.081183,-0.658433,-0.157004,0.142111,-0.547890,-0.044250,...,-0.124443,-0.206095,0.225437,-0.066661,-0.031287,-0.179264,0.042166,0.272938,0.087917,0.148245
3,-1.811530,-0.050414,-0.741775,0.246262,-0.998455,0.497387,0.274187,0.092528,2.618977,-0.173273,...,1.009276,0.317290,-0.168430,-0.546602,-0.348772,-0.801617,-0.153231,0.453455,-0.001869,-0.345558
4,-1.975004,2.125865,0.154781,-1.447695,-2.275162,0.307895,1.449347,-0.374803,0.911421,-0.085424,...,-0.723818,0.162930,0.273418,-0.658179,-0.478855,-0.225696,0.644197,0.889324,0.821254,0.388783
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23371,-3.300214,0.128467,2.003351,-0.482325,1.125966,-0.651860,-0.156288,0.089459,-0.631210,-0.070514,...,0.034896,-0.062628,0.048367,0.014260,-0.047334,0.018585,-0.074244,-0.177157,-0.185205,-0.152972
23372,-3.249073,0.132255,2.024109,-0.445704,1.056170,-0.738531,-0.224631,0.150540,-0.519294,-0.305081,...,0.259774,0.209792,-0.399480,0.164352,0.283408,0.009747,-0.047844,-0.023769,0.029047,0.343595
23373,-3.249073,0.132255,2.024109,-0.445704,1.056170,-0.738531,-0.224631,0.150540,-0.519294,-0.305081,...,0.259774,0.209792,-0.399480,0.164352,0.283408,0.009747,-0.047844,-0.023769,0.029047,0.343595
23374,-3.249073,0.132255,2.024109,-0.445704,1.056170,-0.738531,-0.224631,0.150540,-0.519294,-0.305081,...,0.259774,0.209792,-0.399480,0.164352,0.283408,0.009747,-0.047844,-0.023769,0.029047,0.343595
23375,-3.249178,0.132173,2.023278,-0.444689,1.055428,-0.737447,-0.224545,0.150226,-0.518299,-0.305179,...,0.265184,0.210174,-0.399985,0.162815,0.281576,0.004353,-0.049236,-0.023553,0.028996,0.341337